### PR TITLE
Fix universes

### LINKED ISSUE #1: Predicativity for Pi in turnstile-core
Currently allows impredicativity at all levels, which is inconsistent

Need the following rules:
```
⊢ A : Type i
x,A ⊢ B : Type 0
--------------- Prod-Prop
⊢ Πx:A.B : Type 0

⊢ A : Type j
x,A ⊢ B : Type i
--------------- Prod-Type
⊢ Πx:A.B : Type (max i j)
```

Alternative Prod-Type using subtyping

```
⊢ A : Type i
x,A ⊢ B : Type i
--------------- Prod-Type
⊢ Πx:A.B : Type i
```

### PR DESCRIPTION
**Pull request by wilbowma**
This is not ready to be merged yet, but it fixes #1 and #14 and I want to make note of that on the repo.
However, it makes inference work less well, and isn't on the rebased turnstile-core.
I want to give inference some more thought before I merge it.

### CODE REVIEW

**Comment by stchang** [comment]
Cool.

**Comment by wilbowma** [comment]
Not sure how, but I broke something with resugaring for `->`:
```
 ~/w/cur> raco test cur-test/cur/tests/ntac/admit.rkt
raco test: "cur-test/cur/tests/ntac/admit.rkt"
raco test: @(test-responsible '(wilbowma))
--------------------
FAILURE
name:       check-equal?
location:   admit.rkt:21:0
actual:
  "Axioms used by \"excluded-middle\":\n - ex-mid : (Π (P : (Type 0)) (And P (Π (X1 : P) False)))\n"
expected:
  "Axioms used by \"excluded-middle\":\n - ex-mid : (Π (P : (Type 0)) (And P (→ P False)))\n"
--------------------
1/1 test failures
```

I took a look and fixed one bug, but can't figure out this one.

**Comment by wilbowma** [comment]
Also, excluded middle should be P *or* not P, although it's not really relevant.

**Comment by wilbowma** [comment]
Oh nevermind; I found the bug. `define-binding-type` does some magic that I need to do.

**Comment by wilbowma** [comment]
Looks like the abstraction I introduced to implement \Pi more easily is causing an infinite loop somewhere in `Imp-var.rkt`. Giving up on it for today.

**Comment by wilbowma** [comment]
After an extensive day of debugging, it might not be an infinite loop, but could just be a massive performance problem. `Imp-var` appears to be causing significant expansion, unexpansion, and reexpansion of `Pi`, which might be much slower with the new implementation since it has several cases... Not complete sure.

**Comment by wilbowma** [comment]
Okay I fixed the performance problem by collapsing the two ambiguous branches. I still need to run the whole test suite before merging.

**Comment by wilbowma** [comment]
Also, this requires my patch to Turnstile.

**Comment by wilbowma** [comment]
Okay all tests pass, but I had to modify an error message manually. I'm going to keep it for now, but it seems like something we could create an abstraction for in Turnstile:
https://github.com/stchang/cur/pull/21/files#diff-ff7484617fcab2ef5a9d036a9a144aaeR82

**Comment by stchang** [comment]
merged, starting at 56cf34d93e1852532633038e95c22b9f30cc3917

**Pull request closed without merging**
