### PR TITLE
WIP: Exercises in Logic chapter of LF

### PR DESCRIPTION
**Pull request by iitalics**
Depends on:
- [x] #9 ~~(`by-left`, `by-right`)~~
- [x] #10 ~~(`Not`)~~

### CODE REVIEW

**Comment by iitalics** [comment]
@stchang right now I have everything up to the part about rewrite for arbitrary setoids (namely `iff`).

Let me know if you want to merge this. It is a pretty good test for the new couple of tactics.

**Comment by iitalics** [comment]
PS sorry for not being in the lab today, I am having trouble with NUWave on my laptop

**Comment by stchang** [comment]
ok i will merge

**Comment by stchang** [comment]
https://github.com/stchang/cur/commit/77f6c45a77e449b4e8242bb3cb876adb5a062b9e

**Pull request closed without merging**
